Bookers1/config/routes.rb
Rails.application.routes.draw do
  root 'books#top'
  get 'books/top'
  get 'books/index' 
  get 'books/show'
  get 'books/new'
  get 'books/edit'
  post 'books/:id' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  get 'books/:id/edit' => 'books#show'
  get 'books/:id' => 'books#edit', as: 'edit'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bookers1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers1/app/models/book.rb
class PostCodeValidator < ActiveModel::EachValidator
    def validate_each(title, body)
      record.errors.add(attribute, 'は、数字3桁＋ハイフン（-）＋数字4桁の形式で入力してください。') unless value =~ /\A[0-9]{3}-[0-9]{4}\z/
    end
  end


class Book < ApplicationRecord
    validates :body, presence: true
    validates :title, presence: true
end

Bookers1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers1/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @books = Book.all
    @book = Book.new(book_params) 
    if @book.save
      flash[:notice]="Book was successfully create"
      redirect_to book_path(@book.id)
    else
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    flash[:notice]="Book was successfully update"
    redirect_to book_path(@book.id)
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

Bookers1/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers1/app/helpers/books_helper.rb
module BooksHelper
end

Bookers1/app/views/books/edit.html.erb
<div class="edit">
<h1>Editing Book</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <br>
    <%= f.submit 'Update Book' %>
<% end %>
    <%= link_to 'show', "/books/#{@book.id}" %>
    <p class="edit-menu">|</p>
    <%= link_to 'back', "/books" %>
</div>

Bookers1/app/views/books/index.html.erb
<div class="index-top">
    <h1>Books</h1>
</div>
<main class>
    <table>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
      </tr>
        <% @books.each do |book| %>
          <tbody>
            <tr>
                <td><%= book.title %></td>
                <td><%= book.body %></td>
                <td><%= link_to 'show', book_path(book.id) %></td>
                <td><%= link_to 'edit', edit_book_path(book.id) %></td>
                <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %> </td>
            </tr>
          </tbody>
        <% end %>
    </table>
    <div class="create">
        <h2>New book</h2>
        <%= form_for(@book, url: '/books/index') do |f| %>
          <% if @book.errors.any? %>
            <div class="errore">
                <p class="errore-title"><%= @book.errors.count %>errors prohibited this book from being saved:</p>
                <div class="errore-list">
                  <ul>
                    <% @book.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            </div>
            <div class="errore-Title">
              <h4 class="errore-Title-up">Title</h4>
              <div class="errore-Title-down">
                <%= f.text_field :title, style: "border: none" %>
              </div>
            </div>
            <div class="erroe-Body">
              <h4 class="errore-Body-up">Body</h4>
              <div class="errore-Body-down">
                <%= f.text_area :body, style: "border: none"%>
              </div>
            </div>
            <br>
            <%= f.submit 'Create Book' %>
          <% else %>
            <h4>Title</h4>
            <%= f.text_field :title %>
            <h4>Body</h4>
            <%= f.text_area :body %>
            <br>
            <%= f.submit 'Create Book' %>
          <% end %>
        <% end %>
    </div>
</main>

Bookers1/app/views/books/new.html.erb
<div class="create">
    <h2>New book</h2>
    <%= form_for(@book, url: '/books/new') do |f| %>
        <% @book.errors.full_messages.each do |message| %>
            <%= message %><br>
        <% end %>
            <h4>Title</h4>
            <%= f.text_field :title %>
            <h4>Body</h4>
            <%= f.text_area :body %>
            <br>
            <%= f.submit 'Create Book' %>
    <% end %>
</div>

Bookers1/app/views/books/show.html.erb
<div class="show">
    <div class="show-main">
      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <div class="show-group">
        <p><span style="font-weight:bold">Title</span> <%= @book.title %></p>
      </div>
      <div class="show-group">
        <p><span style="font-weight:bold">Body</span> <%= @book.body %></p>
      </div>
    </div>
    <p class="edit-menu"><%= link_to "Edit", edit_book_path(@book.id) %></p>
    <p class="edit-menu">|</p>
    <%= link_to 'Back', "/books" %>
</div>

Bookers1/app/views/books/top.html.erb
<div class="top-title">
    <h1 >ようこそ Bookersへ！</h1>
</div>
<div class="top-text">
    <p>
    <span style="font-weight:bold">Bookers</span>では、様々な書籍に関するあなたの意見や<br>
    印象を共有し交換することができます。<br>
    </p>
    <%= link_to "start", books_path%>
</div>

Bookers1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>